#!/usr/bin/env python3
"""
Script tự động cập nhật IP LAN cho toàn bộ hệ thống CyberMonitor
Chỉ thay đổi những chỗ CẦN THIẾT để máy khác truy cập được
Giữ nguyên localhost ở những chỗ không cần thiết
"""

import json
import os
import re
import socket
import sys
from pathlib import Path


def get_lan_ip():
    """Lấy IP LAN của máy hiện tại"""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return None


def update_backend_appsettings(ip):
    """
    Cập nhật Backend appsettings.json
    - Urls: Thêm LAN IP để Backend listen trên cả LAN và localhost
    - AllowedHosts: Cho phép truy cập từ LAN
    - Cors: Cho phép Frontend từ LAN
    - AiEngineSettings.BaseUrl: URL của AI Engine
    """
    file_path = Path("Backend/CyberMonitor.API/appsettings.json")
    if not file_path.exists():
        print(f"❌ Không tìm thấy: {file_path}")
        return False
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Backend phải listen trên cả LAN IP và localhost
        data["Urls"] = f"http://{ip}:5000;http://localhost:5000;http://0.0.0.0:5000"
        data["AllowedHosts"] = "*"  # Cho phép tất cả hosts
        
        # CORS: Cho phép Frontend từ LAN
        if "Cors" not in data:
            data["Cors"] = {}
        
        data["Cors"]["AllowedOrigins"] = [
            f"http://{ip}:3000",
            "http://localhost:3000",
            f"http://{ip}:5173",
            "http://localhost:5173",
            f"http://{ip}:4173",
            "http://localhost:4173"
        ]
        
        # AI Engine BaseUrl (nếu AI Engine chạy trên cùng máy)
        if "AiEngineSettings" in data:
            data["AiEngineSettings"]["BaseUrl"] = f"http://{ip}:8000"
        
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        
        print(f"✅ Backend appsettings.json")
        print(f"   ├─ Urls: {ip}:5000 + localhost:5000")
        print(f"   ├─ CORS: {ip}:3000, {ip}:5173")
        print(f"   └─ AI Engine: {ip}:8000")
        return True
    except Exception as e:
        print(f"❌ Lỗi cập nhật Backend: {e}")
        return False


def update_frontend_env(ip):
    """
    Cập nhật Frontend .env
    - VITE_API_URL: URL của Backend API
    - VITE_WS_URL: WebSocket URL (cho SignalR)
    """
    file_path = Path("Frontend/.env")
    
    content = f"""# CyberMonitor Environment Variables
# Auto-generated by setup_lan_network.py

# API URL (Backend)
VITE_API_URL=http://{ip}:5000

# WebSocket URL (SignalR)
VITE_WS_URL=ws://{ip}:5000

# Gemini API Key (optional - for AI features)
"""
    
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"✅ Frontend .env: {ip}:5000")
        return True
    except Exception as e:
        print(f"❌ Lỗi cập nhật Frontend .env: {e}")
        return False


def update_vite_config(ip):
    """
    Cập nhật vite.config.ts để proxy đúng
    Chỉ update nếu cần thiết
    """
    file_path = Path("Frontend/vite.config.ts")
    if not file_path.exists():
        return True
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Thay đổi proxy target
        content = re.sub(
            r"target:\s*['\"]http://localhost:5000['\"]",
            f"target: 'http://{ip}:5000'",
            content
        )
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ Frontend vite.config.ts: proxy → {ip}:5000")
        return True
    except Exception as e:
        print(f"⚠️  Không thể cập nhật vite.config.ts: {e}")
        return True  # Không critical


def update_agent_config(ip):
    """
    Cập nhật Agent config.json
    - backend_url: URL của Backend API
    """
    file_path = Path("Agent/Agent_build_exe/config.json")
    
    try:
        config = {
            "backend_url": f"http://{ip}:5000",
            "api_key": "your-api-key-here",
            "server_id": None,
            "check_interval": 60
        }
        
        # Nếu file đã tồn tại, giữ lại api_key và server_id
        if file_path.exists():
            with open(file_path, 'r', encoding='utf-8') as f:
                old_config = json.load(f)
                config["api_key"] = old_config.get("api_key", config["api_key"])
                config["server_id"] = old_config.get("server_id", config["server_id"])
                config["check_interval"] = old_config.get("check_interval", config["check_interval"])
        
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2, ensure_ascii=False)
        
        print(f"✅ Agent config.json: {ip}:5000")
        return True
    except Exception as e:
        print(f"❌ Lỗi cập nhật Agent config: {e}")
        return False


def update_ai_engine_config(ip):
    """
    Cập nhật AI Engine config
    - backend_url: URL của Backend API
    """
    file_path = Path("Al-Engine/config.json")
    
    try:
        config = {
            "backend_url": f"http://{ip}:5000",
            "api_key": "sk-ai-engine-secret-key-2026",
            "check_interval": 300,
            "anomaly_threshold": 0.7
        }
        
        # Nếu file đã tồn tại, giữ lại settings
        if file_path.exists():
            with open(file_path, 'r', encoding='utf-8') as f:
                old_config = json.load(f)
                config["api_key"] = old_config.get("api_key", config["api_key"])
                config["check_interval"] = old_config.get("check_interval", config["check_interval"])
                config["anomaly_threshold"] = old_config.get("anomaly_threshold", config["anomaly_threshold"])
        
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2, ensure_ascii=False)
        
        print(f"✅ AI Engine config.json: {ip}:5000")
        return True
    except Exception as e:
        print(f"❌ Lỗi cập nhật AI Engine config: {e}")
        return False


def create_quick_start_scripts(ip):
    """Tạo các script khởi động nhanh"""
    
    # Script khởi động Backend
    backend_script = f"""@echo off
chcp 65001 >nul
echo ============================================================
echo 🚀 Starting CyberMonitor Backend
echo ============================================================
echo.
echo Backend URL: http://{ip}:5000
echo Swagger: http://{ip}:5000/swagger
echo.
cd Backend\\CyberMonitor.API
dotnet run
pause
"""
    
    # Script khởi động Frontend
    frontend_script = f"""@echo off
chcp 65001 >nul
echo ============================================================
echo 🚀 Starting CyberMonitor Frontend
echo ============================================================
echo.
echo Frontend URL: http://{ip}:3000
echo Backend API: http://{ip}:5000
echo.
cd Frontend
npm run dev -- --host 0.0.0.0
pause
"""
    
    # Script khởi động Agent
    agent_script = f"""@echo off
chcp 65001 >nul
echo ============================================================
echo 🚀 Starting CyberMonitor Agent
echo ============================================================
echo.
echo Backend URL: http://{ip}:5000
echo.
cd Agent\\Agent_build_exe
python main.py
pause
"""
    
    # Script khởi động AI Engine
    ai_script = f"""@echo off
chcp 65001 >nul
echo ============================================================
echo 🚀 Starting CyberMonitor AI Engine
echo ============================================================
echo.
echo Backend URL: http://{ip}:5000
echo AI Engine Port: 8000
echo.
cd Al-Engine
python ai_engine.py --backend-url http://{ip}:5000
pause
"""
    
    try:
        Path("start_backend.bat").write_text(backend_script, encoding='utf-8')
        Path("start_frontend.bat").write_text(frontend_script, encoding='utf-8')
        Path("start_agent.bat").write_text(agent_script, encoding='utf-8')
        Path("start_ai_engine.bat").write_text(ai_script, encoding='utf-8')
        
        print(f"✅ Đã tạo quick start scripts")
        return True
    except Exception as e:
        print(f"⚠️  Không thể tạo start scripts: {e}")
        return True


def create_access_info(ip):
    """Tạo file thông tin truy cập"""
    content = f"""
╔══════════════════════════════════════════════════════════════╗
║          CyberMonitor - LAN Access Information               ║
╚══════════════════════════════════════════════════════════════╝

📡 LAN IP Address: {ip}

🌐 Access URLs (from other devices on same network):
   ┌─────────────────────────────────────────────────────────┐
   │ Frontend:  http://{ip}:3000                        │
   │ Backend:   http://{ip}:5000                        │
   │ Swagger:   http://{ip}:5000/swagger                │
   │ AI Engine: http://{ip}:8000                        │
   └─────────────────────────────────────────────────────────┘

🚀 Quick Start:
   1. Start Backend:    double-click start_backend.bat
   2. Start Frontend:   double-click start_frontend.bat
   3. Start Agent:      double-click start_agent.bat (optional)
   4. Start AI Engine:  double-click start_ai_engine.bat (optional)

📱 Mobile/Tablet Access:
   - Connect to same WiFi network
   - Open browser and go to: http://{ip}:3000

🔥 Firewall (if needed):
   - Run: open_firewall.bat (as Administrator)
   - Or manually open ports: 3000, 5000, 8000

⚠️  Important Notes:
   - Backend MUST be running before Frontend
   - All devices must be on the same LAN/WiFi
   - If IP changes, run setup_lan_network.bat again

🐛 Troubleshooting:
   - Can't access? Check firewall settings
   - Connection refused? Make sure Backend is running
   - Wrong IP? Run setup_lan_network.bat again

═══════════════════════════════════════════════════════════════
Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
═══════════════════════════════════════════════════════════════
"""
    
    try:
        Path("LAN_ACCESS_INFO.txt").write_text(content, encoding='utf-8')
        print(f"✅ Đã tạo LAN_ACCESS_INFO.txt")
        return True
    except Exception as e:
        print(f"⚠️  Không thể tạo access info: {e}")
        return True


def main():
    print("=" * 70)
    print("🔧 CyberMonitor - LAN Network Setup")
    print("=" * 70)
    
    # Detect IP
    print("\n📡 Detecting LAN IP...")
    lan_ip = get_lan_ip()
    
    if not lan_ip:
        print("❌ Không thể detect IP LAN!")
        print("💡 Vui lòng nhập IP thủ công:")
        lan_ip = input("   IP: ").strip()
        if not lan_ip:
            print("❌ Không có IP, thoát!")
            sys.exit(1)
    
    print(f"✅ Detected IP: {lan_ip}")
    print(f"\n🔄 Updating configuration files...\n")
    
    # Update all configs
    results = []
    results.append(("Backend appsettings.json", update_backend_appsettings(lan_ip)))
    results.append(("Frontend .env", update_frontend_env(lan_ip)))
    results.append(("Frontend vite.config.ts", update_vite_config(lan_ip)))
    results.append(("Agent config.json", update_agent_config(lan_ip)))
    results.append(("AI Engine config.json", update_ai_engine_config(lan_ip)))
    results.append(("Quick start scripts", create_quick_start_scripts(lan_ip)))
    results.append(("Access info file", create_access_info(lan_ip)))
    
    # Summary
    print("\n" + "=" * 70)
    print("📊 SUMMARY")
    print("=" * 70)
    
    success_count = sum(1 for _, success in results if success)
    total_count = len(results)
    
    for name, success in results:
        status = "✅" if success else "❌"
        print(f"{status} {name}")
    
    print(f"\n✅ Success: {success_count}/{total_count}")
    
    if success_count >= 5:  # At least core configs updated
        print("\n" + "=" * 70)
        print("🎉 SETUP COMPLETE!")
        print("=" * 70)
        print(f"\n🌐 Access from other devices:")
        print(f"   Frontend: http://{lan_ip}:3000")
        print(f"   Backend:  http://{lan_ip}:5000")
        print(f"   Swagger:  http://{lan_ip}:5000/swagger")
        
        print(f"\n🚀 Next steps:")
        print(f"   1. Open Firewall: open_firewall.bat (as Administrator)")
        print(f"   2. Start Backend:  start_backend.bat")
        print(f"   3. Start Frontend: start_frontend.bat")
        print(f"   4. Access from other device: http://{lan_ip}:3000")
        
        print(f"\n📄 See LAN_ACCESS_INFO.txt for detailed instructions")
    else:
        print("\n⚠️  Some files could not be updated!")
        print("Please check the errors above and try again.")
    
    print("=" * 70)


if __name__ == "__main__":
    main()
